CREATE TABLE IF NOT EXISTS bangumi_anime (
  id BIGINT PRIMARY KEY,
  name_jp VARCHAR(512),
  name_cn VARCHAR(512),
  name_en VARCHAR(512) NULL,
  type VARCHAR(32),
  platform INT NULL,
  air_date DATE NULL,
  air_year INT NULL,
  air_month INT NULL,
  air_weekday VARCHAR(64) NULL,
  raw_air_date VARCHAR(128) NULL,
  eps INT NULL,
  summary TEXT,
  rating_score FLOAT NULL,
  rating_count INT NULL,
  `rank` INT NULL,
  image_small TEXT NULL,
  image_large TEXT NULL,
  cover_local_path TEXT NULL,
  broadcast TEXT NULL,
  tags_json JSON,
  meta_tags_json JSON,
  infobox_json JSON,
  raw_infobox MEDIUMTEXT,
  nsfw BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_air_year_month (air_year, air_month),
  FULLTEXT INDEX ft_names (name_jp, name_cn, name_en)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
